# Generated by Django 5.1.6 on 2025-02-22 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRaktar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='store',
        ),
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appRaktar.store'),
        ),
        migrations.AddField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
